#!/usr/bin/python
import sys
import time
from t2Mon.hdfs.datanode import execute
from t2Mon.daemon import Daemon

class MyDaemon(Daemon):
    def run(self, runTimer):
        while True:
            startTime = int(time.time())
            execute()
            endTime = int(time.time())
            sleepTime = int(runTimer - (endTime - startTime))
            print 'Sleeping %s seconds' % sleepTime
            time.sleep(int(sleepTime))

if __name__ == "__main__":
    daemonName = 'datanode-mon'
    daemon =  MyDaemon('/tmp/daemon-%s.pid' % daemonName,
                       stdout='/var/log/t2Mon/%s/std.out' % daemonName,
                       stderr='/var/log/t2Mon/%s/std.err' % daemonName)
    if len(sys.argv) >= 2:
        if sys.argv[1] == 'start':
            if len(sys.argv) != 3:
                print 'Usage: %s start runTimer' % sys.argv[0]
                sys.exit(2)
            daemon.start(sys.argv[3])
        elif sys.argv[1] == 'stop':
            daemon.stop()
        elif sys.argv[1] == 'restart':
            print 'Usage: %s start runTimer' % sys.argv[0]
            daemon.restart(sys.argv[3])
        elif sys.argv[1] == 'status':
            daemon.status()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|status|restart [runTimer]" % sys.argv[0]
        sys.exit(2)
