#!/usr/bin/python
import sys
import time
from t2Mon.compute.computeSAM import execute
from t2Mon.daemon import Daemon

class MyDaemon(Daemon):
    def run(self):
        while True:
            try:
                print execute()
                print 'Sleeping 5 minutes'
                time.sleep(600)
            except:
                print 'Got exception...'
                time.sleep(600)

if __name__ == "__main__":
    daemonName = 'samtest-local'
    daemon =  MyDaemon('/tmp/daemon-%s.pid' % daemonName,
                       stdout='/var/log/t2Mon/%s/std.out' % daemonName,
                       stderr='/var/log/t2Mon/%s/std.err' % daemonName)
    if len(sys.argv) == 2:
        if sys.argv[1] == 'start':
            daemon.start()
        elif sys.argv[1] == 'stop':
            daemon.stop()
        elif sys.argv[1] == 'restart':
            daemon.restart()
        elif sys.argv[1] == 'status':
            daemon.status()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|status|restart" % sys.argv[0]
        sys.exit(2)

# TODO. Allow to control timer how often...